---

- name: testing docker container network
  command: docker network inspect {{ network_name }}
  register: network
  ignore_errors: yes

- name: create docker container network
  command: docker network create --subnet {{ subnet }} {{ network_name }}
  when: network.rc == 1
