---
- name: testing docker container
  command: docker inspect {{ docker_name }}
  register: container
  ignore_errors: yes

- name: stop docker container
  command: docker stop {{ docker_name }}
  when: container.rc == 0

- name: remove docker container
  command: docker rm {{ docker_name }}
  when: container.rc == 0

- name: create docker container
  command: docker run -dit --name {{ docker_name }} --hostname {{ docker_name }} --ip {{docker_network_ip }} -p {{ docker_network_port }} --net {{ docker_network }} --add-host=puppet:192.168.200.50 {{docker_image }} /bin/bash
